-- This script inserts initial data into the application's tables.
-- The data is inserted in a specific order to satisfy foreign key constraints.

-- Use a variable to hold the current timestamp for consistent created_time and updated_time values.
-- This is a good practice for ensuring data integrity and consistency.
SET time.timezone = 'UTC';

-- ====================================================================
-- Insert data into the 'users' table
-- Note: 'id' is auto-generated by the database.
-- ====================================================================

-- Insert a Venue Owner
INSERT INTO users (name, birth_date, email, mobile_number, password, role, user_status, created_time, updated_time)
VALUES ('John Doe', '1985-05-20', 'john.doe@example.com', '9876543210', 'hashed_password_1', 'OWNER', 'ACTIVE', NOW(), NOW());

-- Insert a Player
INSERT INTO users (name, birth_date, email, mobile_number, password, role, user_status, created_time, updated_time)
VALUES ('Jane Smith', '1990-08-15', 'jane.smith@example.com', '9876543211', 'hashed_password_2', 'PLAYER', 'ACTIVE', NOW(), NOW());

-- Insert another Player
INSERT INTO users (name, birth_date, email, mobile_number, password, role, user_status, created_time, updated_time)
VALUES ('Peter Jones', '1992-03-25', 'peter.jones@example.com', '9876543212', 'hashed_password_3', 'PLAYER', 'ACTIVE', NOW(), NOW());

-- ====================================================================
-- Insert data into the 'sports' table
-- ====================================================================

INSERT INTO sports (name, created_time, updated_time)
VALUES ('Cricket', NOW(), NOW());

INSERT INTO sports (name, created_time, updated_time)
VALUES ('Football', NOW(), NOW());

INSERT INTO sports (name, created_time, updated_time)
VALUES ('Tennis', NOW(), NOW());


-- ====================================================================
-- Insert data into the 'venues' table
--
-- This requires a user to be an owner. We'll use a subquery to find the owner's ID.
-- ====================================================================

INSERT INTO venues (name, city, address, mobile_number, owner_id, type, created_time, updated_time)
VALUES ('City Sports Arena', 'Mumbai', '123 Main Street', '9998887776', (SELECT id FROM users WHERE email = 'john.doe@example.com'), 'Indoor', NOW(), NOW());


-- ====================================================================
-- Insert data into the 'facilities' table
--
-- This requires an existing venue and sports. We'll use subqueries to get their IDs.
-- ====================================================================

INSERT INTO facilities (name, venue_id, sport_id, price_per_hour, created_time, updated_time)
VALUES ('Cricket Pitch 1', (SELECT id FROM venues WHERE name = 'City Sports Arena'), (SELECT id FROM sports WHERE name = 'Cricket'), 500.00, NOW(), NOW());

INSERT INTO facilities (name, venue_id, sport_id, price_per_hour, created_time, updated_time)
VALUES ('Football Field 1', (SELECT id FROM venues WHERE name = 'City Sports Arena'), (SELECT id FROM sports WHERE name = 'Football'), 800.00, NOW(), NOW());


-- ====================================================================
-- Insert data into the 'slots' table
--
-- This requires an existing facility. We'll use a subquery to get its ID.
-- ====================================================================

-- Slots for Cricket Pitch 1
INSERT INTO slots (start_time, end_time, facility_id, is_booked, created_time, updated_time)
VALUES ('2025-09-01 10:00:00', '2025-09-01 11:00:00', (SELECT id FROM facilities WHERE name = 'Cricket Pitch 1'), FALSE, NOW(), NOW());

INSERT INTO slots (start_time, end_time, facility_id, is_booked, created_time, updated_time)
VALUES ('2025-09-01 11:00:00', '2025-09-01 12:00:00', (SELECT id FROM facilities WHERE name = 'Cricket Pitch 1'), TRUE, NOW(), NOW());


-- ====================================================================
-- Insert data into the 'bookings' table
--
-- This requires an existing slot and user (player). We'll use subqueries.
-- ====================================================================

INSERT INTO bookings (slot_id, player_id, booking_time, status, created_time, updated_time)
VALUES ((SELECT id FROM slots WHERE start_time = '2025-09-01 11:00:00' AND is_booked = TRUE), (SELECT id FROM users WHERE email = 'jane.smith@example.com'), NOW(), 'CONFIRMED', NOW(), NOW());
